### ISSUE TITLE
PathCamera starting position issue

### ISSUE THREAD

**Issue by marcomarchesi** [marcomarchesi/threejs-boilerplate-plus#2]
@PierfrancescoSoffritti 
Non posso fare una pull request, troppe differenze tra i nostri branch `develop` e il procedimento per fare la pull sarebbe un po' laborioso. Quindi ti allego semplicemente la soluzione. 
Una volta instanziata la PathCamera,
`path = new PathCamera(pathCamera, sampleClosedSpline);`
aggiungi semplicemente questo:
`path.update(0,controlGUI.oculusEnabled);`

Ciao
Marco

**Comment by PierfrancescoSoffritti** [comment]
ok!
